// <auto-generated />
using System;
using CareerOrientationAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HuongnghiepAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251208033836_AddRoleToStudentAndCounselor")]
    partial class AddRoleToStudentAndCounselor
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CareerOrientationAPI.Models.Answer", b =>
                {
                    b.Property<int>("AnswerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnswerId"));

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("AnswerId");

                    b.HasIndex("QuestionId");

                    b.ToTable("Answers");
                });

            modelBuilder.Entity("CareerOrientationAPI.Models.AnswerImpact", b =>
                {
                    b.Property<int>("ImpactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImpactId"));

                    b.Property<int>("AnswerId")
                        .HasColumnType("int");

                    b.Property<int>("ImpactValue")
                        .HasColumnType("int");

                    b.Property<int>("MajorId")
                        .HasColumnType("int");

                    b.Property<int>("MajorTraitId")
                        .HasColumnType("int");

                    b.HasKey("ImpactId");

                    b.HasIndex("AnswerId");

                    b.HasIndex("MajorId");

                    b.HasIndex("MajorTraitId");

                    b.ToTable("AnswerImpacts");
                });

            modelBuilder.Entity("CareerOrientationAPI.Models.CounselingSchedule", b =>
                {
                    b.Property<int>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScheduleId"));

                    b.Property<DateTime>("BookingTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("CounselorId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("ScheduleId");

                    b.HasIndex("CounselorId");

                    b.ToTable("CounselingSchedules");
                });

            modelBuilder.Entity("CareerOrientationAPI.Models.Counselor", b =>
                {
                    b.Property<int>("CounselorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CounselorId"));

                    b.Property<string>("Details")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CounselorId");

                    b.ToTable("Counselors");
                });

            modelBuilder.Entity("CareerOrientationAPI.Models.Major", b =>
                {
                    b.Property<int>("MajorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MajorId"));

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("MajorId");

                    b.ToTable("Majors");
                });

            modelBuilder.Entity("CareerOrientationAPI.Models.MajorSubField", b =>
                {
                    b.Property<int>("SubFieldId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubFieldId"));

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("MajorId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("SubFieldId");

                    b.HasIndex("MajorId");

                    b.ToTable("MajorSubFields");
                });

            modelBuilder.Entity("CareerOrientationAPI.Models.MajorTrait", b =>
                {
                    b.Property<int>("TraitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TraitId"));

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("MajorId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("TraitId");

                    b.HasIndex("MajorId");

                    b.ToTable("MajorTraits");
                });

            modelBuilder.Entity("CareerOrientationAPI.Models.Question", b =>
                {
                    b.Property<int>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuestionId"));

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int>("QuestionGroupId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("QuestionId");

                    b.HasIndex("QuestionGroupId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("CareerOrientationAPI.Models.QuestionGroup", b =>
                {
                    b.Property<int>("QuestionGroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuestionGroupId"));

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("QuestionGroupId");

                    b.ToTable("QuestionGroups");
                });

            modelBuilder.Entity("CareerOrientationAPI.Models.Roadmap", b =>
                {
                    b.Property<int>("RoadmapId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoadmapId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MajorId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("RoadmapId");

                    b.HasIndex("MajorId");

                    b.ToTable("Roadmaps");
                });

            modelBuilder.Entity("CareerOrientationAPI.Models.RoadmapItem", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemId"));

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ItemOrder")
                        .HasColumnType("int");

                    b.Property<string>("ItemTitle")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ResourceLink")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("StageId")
                        .HasColumnType("int");

                    b.HasKey("ItemId");

                    b.HasIndex("StageId");

                    b.ToTable("RoadmapItems");
                });

            modelBuilder.Entity("CareerOrientationAPI.Models.RoadmapSkill", b =>
                {
                    b.Property<int>("SkillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SkillId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<string>("SkillName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("SkillId");

                    b.HasIndex("ItemId");

                    b.ToTable("RoadmapSkills");
                });

            modelBuilder.Entity("CareerOrientationAPI.Models.RoadmapStage", b =>
                {
                    b.Property<int>("StageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StageId"));

                    b.Property<int>("RoadmapId")
                        .HasColumnType("int");

                    b.Property<string>("StageDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StageOrder")
                        .HasColumnType("int");

                    b.Property<string>("StageTitle")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("StageId");

                    b.HasIndex("RoadmapId");

                    b.ToTable("RoadmapStages");
                });

            modelBuilder.Entity("CareerOrientationAPI.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Gender")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("Grade")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("School")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("StudentId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("CareerOrientationAPI.Models.TestAnswer", b =>
                {
                    b.Property<int>("TestAnswerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TestAnswerId"));

                    b.Property<int>("AnswerId")
                        .HasColumnType("int");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<int>("TestResultId")
                        .HasColumnType("int");

                    b.HasKey("TestAnswerId");

                    b.HasIndex("AnswerId");

                    b.HasIndex("QuestionId");

                    b.HasIndex("TestResultId");

                    b.ToTable("TestAnswers");
                });

            modelBuilder.Entity("CareerOrientationAPI.Models.TestAnswerImpact", b =>
                {
                    b.Property<int>("TestAnswerImpactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TestAnswerImpactId"));

                    b.Property<int>("ImpactValue")
                        .HasColumnType("int");

                    b.Property<int>("MajorId")
                        .HasColumnType("int");

                    b.Property<int>("MajorTraitId")
                        .HasColumnType("int");

                    b.Property<int>("TestAnswerId")
                        .HasColumnType("int");

                    b.HasKey("TestAnswerImpactId");

                    b.HasIndex("MajorId");

                    b.HasIndex("MajorTraitId");

                    b.HasIndex("TestAnswerId");

                    b.ToTable("TestAnswerImpacts");
                });

            modelBuilder.Entity("CareerOrientationAPI.Models.TestResult", b =>
                {
                    b.Property<int>("TestResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TestResultId"));

                    b.Property<int?>("CounselorId")
                        .HasColumnType("int");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("int");

                    b.Property<int?>("StudentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("TestResultId");

                    b.HasIndex("CounselorId");

                    b.HasIndex("StudentId");

                    b.ToTable("TestResults");
                });

            modelBuilder.Entity("CareerOrientationAPI.Models.TestResultMajorScore", b =>
                {
                    b.Property<int>("ScoreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScoreId"));

                    b.Property<int>("MajorId")
                        .HasColumnType("int");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<int>("TestResultId")
                        .HasColumnType("int");

                    b.HasKey("ScoreId");

                    b.HasIndex("MajorId");

                    b.HasIndex("TestResultId");

                    b.ToTable("TestResultMajorScores");
                });

            modelBuilder.Entity("Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("NotificationId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("CareerOrientationAPI.Models.Answer", b =>
                {
                    b.HasOne("CareerOrientationAPI.Models.Question", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("CareerOrientationAPI.Models.AnswerImpact", b =>
                {
                    b.HasOne("CareerOrientationAPI.Models.Answer", "Answer")
                        .WithMany("Impacts")
                        .HasForeignKey("AnswerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CareerOrientationAPI.Models.Major", "Major")
                        .WithMany("AnswerImpacts")
                        .HasForeignKey("MajorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CareerOrientationAPI.Models.MajorTrait", "MajorTrait")
                        .WithMany()
                        .HasForeignKey("MajorTraitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Answer");

                    b.Navigation("Major");

                    b.Navigation("MajorTrait");
                });

            modelBuilder.Entity("CareerOrientationAPI.Models.CounselingSchedule", b =>
                {
                    b.HasOne("CareerOrientationAPI.Models.Counselor", "Counselor")
                        .WithMany("Schedules")
                        .HasForeignKey("CounselorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Counselor");
                });

            modelBuilder.Entity("CareerOrientationAPI.Models.MajorSubField", b =>
                {
                    b.HasOne("CareerOrientationAPI.Models.Major", "Major")
                        .WithMany()
                        .HasForeignKey("MajorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Major");
                });

            modelBuilder.Entity("CareerOrientationAPI.Models.MajorTrait", b =>
                {
                    b.HasOne("CareerOrientationAPI.Models.Major", "Major")
                        .WithMany("MajorTraits")
                        .HasForeignKey("MajorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Major");
                });

            modelBuilder.Entity("CareerOrientationAPI.Models.Question", b =>
                {
                    b.HasOne("CareerOrientationAPI.Models.QuestionGroup", "QuestionGroup")
                        .WithMany("Questions")
                        .HasForeignKey("QuestionGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuestionGroup");
                });

            modelBuilder.Entity("CareerOrientationAPI.Models.Roadmap", b =>
                {
                    b.HasOne("CareerOrientationAPI.Models.Major", "Major")
                        .WithMany()
                        .HasForeignKey("MajorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Major");
                });

            modelBuilder.Entity("CareerOrientationAPI.Models.RoadmapItem", b =>
                {
                    b.HasOne("CareerOrientationAPI.Models.RoadmapStage", "Stage")
                        .WithMany("Items")
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stage");
                });

            modelBuilder.Entity("CareerOrientationAPI.Models.RoadmapSkill", b =>
                {
                    b.HasOne("CareerOrientationAPI.Models.RoadmapItem", "Item")
                        .WithMany("Skills")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("CareerOrientationAPI.Models.RoadmapStage", b =>
                {
                    b.HasOne("CareerOrientationAPI.Models.Roadmap", "Roadmap")
                        .WithMany("Stages")
                        .HasForeignKey("RoadmapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Roadmap");
                });

            modelBuilder.Entity("CareerOrientationAPI.Models.TestAnswer", b =>
                {
                    b.HasOne("CareerOrientationAPI.Models.Answer", "Answer")
                        .WithMany()
                        .HasForeignKey("AnswerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CareerOrientationAPI.Models.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CareerOrientationAPI.Models.TestResult", "TestResult")
                        .WithMany("TestAnswers")
                        .HasForeignKey("TestResultId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Answer");

                    b.Navigation("Question");

                    b.Navigation("TestResult");
                });

            modelBuilder.Entity("CareerOrientationAPI.Models.TestAnswerImpact", b =>
                {
                    b.HasOne("CareerOrientationAPI.Models.Major", "Major")
                        .WithMany()
                        .HasForeignKey("MajorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CareerOrientationAPI.Models.MajorTrait", "MajorTrait")
                        .WithMany()
                        .HasForeignKey("MajorTraitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CareerOrientationAPI.Models.TestAnswer", "TestAnswer")
                        .WithMany("Impacts")
                        .HasForeignKey("TestAnswerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Major");

                    b.Navigation("MajorTrait");

                    b.Navigation("TestAnswer");
                });

            modelBuilder.Entity("CareerOrientationAPI.Models.TestResult", b =>
                {
                    b.HasOne("CareerOrientationAPI.Models.Counselor", null)
                        .WithMany("ViewedResults")
                        .HasForeignKey("CounselorId");

                    b.HasOne("CareerOrientationAPI.Models.Student", "Student")
                        .WithMany("TestResults")
                        .HasForeignKey("StudentId");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("CareerOrientationAPI.Models.TestResultMajorScore", b =>
                {
                    b.HasOne("CareerOrientationAPI.Models.Major", "Major")
                        .WithMany("TestResultScores")
                        .HasForeignKey("MajorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CareerOrientationAPI.Models.TestResult", "TestResult")
                        .WithMany("MajorScores")
                        .HasForeignKey("TestResultId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Major");

                    b.Navigation("TestResult");
                });

            modelBuilder.Entity("CareerOrientationAPI.Models.Answer", b =>
                {
                    b.Navigation("Impacts");
                });

            modelBuilder.Entity("CareerOrientationAPI.Models.Counselor", b =>
                {
                    b.Navigation("Schedules");

                    b.Navigation("ViewedResults");
                });

            modelBuilder.Entity("CareerOrientationAPI.Models.Major", b =>
                {
                    b.Navigation("AnswerImpacts");

                    b.Navigation("MajorTraits");

                    b.Navigation("TestResultScores");
                });

            modelBuilder.Entity("CareerOrientationAPI.Models.Question", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("CareerOrientationAPI.Models.QuestionGroup", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("CareerOrientationAPI.Models.Roadmap", b =>
                {
                    b.Navigation("Stages");
                });

            modelBuilder.Entity("CareerOrientationAPI.Models.RoadmapItem", b =>
                {
                    b.Navigation("Skills");
                });

            modelBuilder.Entity("CareerOrientationAPI.Models.RoadmapStage", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("CareerOrientationAPI.Models.Student", b =>
                {
                    b.Navigation("TestResults");
                });

            modelBuilder.Entity("CareerOrientationAPI.Models.TestAnswer", b =>
                {
                    b.Navigation("Impacts");
                });

            modelBuilder.Entity("CareerOrientationAPI.Models.TestResult", b =>
                {
                    b.Navigation("MajorScores");

                    b.Navigation("TestAnswers");
                });
#pragma warning restore 612, 618
        }
    }
}
